<?php

return [
    'group_keys' => [
        'title_pages' => [
            'posts' => ['en' => 'Posts', 'de' => 'Berichten'],
            'contact_us' => ['en' => 'Contact','de' => 'Contact'],
            'about_us' => ['en' => 'About Us','de' => 'Over ons'],
            'products' => ['en' => 'Products','de' => 'producten'],
        ],
        'breadcrumb_pages' => [
            'home' => ['en' => 'Home','de' => 'Thuis'],
            'posts' => ['en' => 'Our Posts','de' => 'onze posten'],
            'contact_us' => ['en' => 'Contact us','de' => 'Neem contact met ons op'],
            'search' => ['en' => 'Search','de' => 'Zoekopdracht'],
            'about_us' => ['en' => 'About Us','de' => 'Over ons'],
            'products' => ['en' => 'Our Products','de' => 'Onze producten'],
        ],
        'actions' => [
            'contact_btn' => ['en' => 'Send Message','de' => 'Bericht versturen'],
            'click_to_call' => ['en' => 'Click to Call','de' => 'Klik om te bellen'],
            'posts_found_for_you' => ['en' => 'Posts found for you','de' => 'Berichten voor jou gevonden'],
            'products_found_for_you' => ['en' => 'Products found for you','de' => 'Producten gevonden voor jou'],
            'we_couldnt_find' => ['en' => 'We couldn\'t find anything related for you','de' => 'We couldn\'t find anything related for you'],
            'follow_us' => ['en' => 'Follow Us','de' => 'Volg ons'],
            'phone' => ['en' => 'Phone','de' => 'telefoon'],
            'email' => ['en' => 'Email','de' => 'E-mail'],
            'languages' => ['en' => 'Languages','de' => 'Talen'],
            'logo' => ['en' => 'Logo','de' => 'Logo'],
            'admin' => ['en' => 'Admin','de' => 'beheerder'],
            'location' => ['en' => 'Location','de' => 'Plaats'],
            'navigation' => ['en' => 'Navigation','de' => 'Navigatie'],
            'related_products' => ['en' => 'Related Products','de' => 'gerelateerde producten'],
            'related_products_subtext' => ['en' => 'You may like these products too...','de' => 'Misschien vind je deze producten ook leuk...'],
            'latest_posts' => ['en' => 'Latest posts','de' => 'Laatste berichten'],
            'contact_head' => ['en' => 'Get In Touch','de' => 'Neem contact op'],
            'contact_subtext' => ['en' => 'Feel free to ask me any question or let\'s do to talk about our future collaboration.','de' => 'Stel me gerust een vraag of laten we praten over onze toekomstige samenwerking.'],
            'contact_request_success' => ['en' => 'Your request sent successfully. we will review and contact you','de' => 'Your request sent successfully. we will review and contact you'],
            'contact_request_success_header' => ['en' => 'Alright!','de' => 'Alright!'],
            'your_name' => ['en' => 'Your Name','de' => 'Uw naam'],
            'your_email' => ['en' => 'Your Email','de' => 'Jouw email'],
            'subject' => ['en' => 'Subject','de' => 'Onderwerp'],
            'write_message' => ['en' => 'Write Message','de' => 'Schrijf een bericht'],
            'view_details' => ['en' => 'View Details','de' => 'Details bekijken'],
            'read_more' => ['en' => 'Read More','de' => 'Lees verder'],
            'send_message' => ['en' => 'Send Message','de' => 'Bericht versturen'],
            'more_details' => ['en' => 'More Details','de' => 'Meer details'],
        ],

        'titles' => [
            'app_name' => ['en' => 'Ductcen','de' => 'Ductcen',],
            'contact_us' => ['en' => 'Contact Info','de' => 'Contact Info',],
            'dashboard' => ['en' => 'Ductcen', 'de' => 'Ductcen'],
            'app' => ['en' => 'Holding Ductcen','de' => 'Holding Ductcen',],
        ],
        'contact_modal' => [
            'title' => ['en' => 'Request A Quote','de' => 'Request A Quote'],
            'success_msg' => ['en' => 'Your message was successfully recorded and queued','de' => 'Your message was successfully recorded and queued'],
            'fail_msg' => ['en' => 'Error registering information - please try again','de' => 'Error registering information - please try again'],
            'btn_send' => ['en' => 'Submit','de' => 'Submit'],
            'field_label_name' => ['en' => 'Your Name', 'de' => 'Your Name'],
            'field_label_email' => ['en' => 'Your Email', 'de' => 'Your Email'],
            'field_label_subject' => ['en' => 'Subject','de' => 'Subject'],
            'field_label_message' => ['en' => 'Your Message', 'de' => 'Your Message'],
            'field_validate_name' => ['en' => 'Name Is Required','de' => 'Name Is Required'],
            'field_validate_email' => ['en' => 'Email Is Required','de' => 'Email Is Required'],
            'field_validate_subject' => ['en' => 'Subject Is Required','de' => 'Subject Is Required'],
            'field_validate_message' => ['en' => 'Message Is Required','de' => 'Message Is Required'],
        ],
        'search_modal' => [
            'title' => ['en' => 'What are you looking for?','de' => 'Waar bent u naar op zoek?'],
            'placeholder' => ['en' => 'Search Products, Posts...','de' => 'Zoek producten, berichten...'],
            'search_btn' => ['en' => 'Search' , 'de' => 'Zoekopdracht'],
            'results_for' => ['en' => 'Results For ','de' => 'results for de'],
            'search_results' => ['en' => 'Search Results','de' => 'Search Results' ]
        ],
        'order_modal' => [
            'title' => ['en' => 'Order Now!','de' => 'Bestel nu!'],
            'order_now' => ['en' => 'Order Now!','de' => 'Bestel nu!'],
            'order_now_subtext' => ['en' => 'Fill this form below. We will contact you ASAP!','de' => 'Bestel nu!'],
            'price' => ['en' => ' Price','de' => 'Prijs'],
            'description' => ['en' => ' Description','de' => 'Beschrijving'],
            'success_msg' => ['en' => 'Your order sent successfully. we will contact you','de' => 'Your message was successfully recorded and queued'],
            'success_msg_title' => ['en' => 'Alright!','de' => 'Alright!'],
            'fail_msg' => ['en' => 'Error Storing information - please try again','de' => 'Error registering information - please try again'],
            'btn_send' => ['en' => 'Submit','de' => 'Submit'],
            'field_label_name' => ['en' => 'Your Name', 'de' => 'Your Name'],
            'field_label_email' => ['en' => 'Your Email', 'de' => 'Your Email'],
            'field_label_subject' => ['en' => 'Subject','de' => 'Subject'],
            'field_label_message' => ['en' => 'Hey I\'d Like to buy this please contact me', 'de' => 'Your Message'],
            'field_validate_name' => ['en' => 'Name Is Required','de' => 'Name Is Required'],
            'field_validate_email' => ['en' => 'Email Is Required','de' => 'Email Is Required'],
            'field_validate_subject' => ['en' => 'Subject Is Required','de' => 'Subject Is Required'],
            'field_validate_message' => ['en' => 'Message Is Required','de' => 'Message Is Required'],
        ],
        'header' => [
            'search_place_holder' => ['en' => 'Search', 'de' => 'Search'],
        ],
        'footer' => [
            'about_company' => ['en' => 'About Company', 'de' => 'About Company'],
            'links' => ['en' => 'Links', 'de' => 'Links'],
            'contact_info' => ['en' => 'Contacts','de' => 'Contacts'],
            'office_label' => ['en' => 'Office Address', 'de' => 'Office Address'],
            'tell_label' => ['en' => 'Telephone','de' => 'Telephone'],
            'email_label' => ['en' => 'Email','de' => 'Email'],
        ],
        'blog_side_bar' => [
            'search_place_holder' => ['en' => 'Search Here','de' => 'Zoek hier'],
            'search_title' => ['en' => 'Search From Blog','de' => 'Zoeken vanuit blog'],
            'category_title' => ['en' => 'Category','de' => 'Category'],
            'recently_new_title' => ['en' => 'Recent Posts','de' => 'Recente berichten'],
            'tags_title' => ['en' => 'Tags','de' => 'Tags'],
            'social_title' => ['en' => 'Social Media','de' => 'Social Media'],
            'post_categories' => ['en' => 'Post Categories','de' => 'Categorieën posten'],
            'comments' => ['en' => 'Comments','de' => 'Opmerkingen'],
            'date' => ['en' => 'Date','de' => 'Datum'],
            'posted_by' => ['en' => 'Posted By','de' => 'Gepost door'],
            'leave_comment' => ['en' => 'Leave A Comment','de' => 'Laat een reactie achter'],
            'leave_comment_subtext' => ['en' => 'Your email address will not be published.','de' => 'Uw e-mailadres wordt niet gepubliceerd.'],
            'leave_comment_success' => ['en' => 'Your comment added successfully. we will review and show your comment' , 'de' => 'Your comment added successfully. we will review and show your comment'],
            'leave_comment_success_header' => ['en' => 'Alright!' , 'de' => 'Alright!'],
        ],
    ],

    'locales' => [
        'fa',
        'en',
        'ad',
        'ae',
        'af',
        'ag',
        'ai',
        'al',
        'am',
        'ao',
        'aq',
        'ar',
        'as',
        'at',
        'au',
        'aw',
        'ax',
        'az',
        'ba',
        'bb',
        'bd',
        'be',
        'bf',
        'bg',
        'bh',
        'bi',
        'bj',
        'bl',
        'bm',
        'bn',
        'bo',
        'bq',
        'br',
        'bs',
        'bt',
        'bv',
        'bw',
        'by',
        'bz',
        'ca',
        'cc',
        'cd',
        'cf',
        'cg',
        'ch',
        'ci',
        'ck',
        'cl',
        'cm',
        'cn',
        'co',
        'cr',
        'cu',
        'cv',
        'cw',
        'cx',
        'cy',
        'cz',
        'de',
        'dj',
        'dk',
        'dm',
        'do',
        'dz',
        'ec',
        'ee',
        'eg',
        'eh',
        'er',
        'es',
        'et',
        'fi',
        'fj',
        'fk',
        'fm',
        'fo',
        'fr',
        'ga',
        'gd',
        'ge',
        'gf',
        'gg',
        'gh',
        'gi',
        'gl',
        'gm',
        'gn',
        'gp',
        'gq',
        'gr',
        'gs',
        'gt',
        'gu',
        'gw',
        'gy',
        'hk',
        'hm',
        'hn',
        'hr',
        'ht',
        'hu',
        'id',
        'ie',
        'il',
        'im',
        'in',
        'io',
        'iq',
        'ir',
        'is',
        'it',
        'je',
        'jm',
        'jo',
        'jp',
        'ke',
        'kg',
        'kh',
        'ki',
        'km',
        'kn',
        'kp',
        'kr',
        'kw',
        'ky',
        'kz',
        'la',
        'lb',
        'lc',
        'li',
        'lk',
        'lr',
        'ls',
        'lt',
        'lu',
        'lv',
        'ly',
        'ma',
        'mc',
        'md',
        'me',
        'mf',
        'mg',
        'mh',
        'mk',
        'ml',
        'mm',
        'mn',
        'mo',
        'mp',
        'mq',
        'mr',
        'ms',
        'mt',
        'mu',
        'mv',
        'mw',
        'mx',
        'my',
        'mz',
        'na',
        'nc',
        'ne',
        'nf',
        'ng',
        'ni',
        'nl',
        'no',
        'np',
        'nr',
        'nu',
        'nz',
        'om',
        'pa',
        'pe',
        'pf',
        'pg',
        'ph',
        'pk',
        'pl',
        'pm',
        'pn',
        'pr',
        'ps',
        'pt',
        'pw',
        'py',
        'qa',
        're',
        'ro',
        'rs',
        'ru',
        'rw',
        'sa',
        'sb',
        'sc',
        'sd',
        'se',
        'sg',
        'sh',
        'si',
        'sj',
        'sk',
        'sl',
        'sm',
        'sn',
        'so',
        'sr',
        'ss',
        'st',
        'sv',
        'sx',
        'sy',
        'sz',
        'tc',
        'td',
        'tf',
        'tg',
        'th',
        'tj',
        'tk',
        'tl',
        'tm',
        'tn',
        'to',
        'tr',
        'tt',
        'tv',
        'tw',
        'tz',
        'ua',
        'ug',
        'um',
        'us',
        'uy',
        'uz',
        'va',
        'vc',
        've',
        'vg',
        'vi',
        'vn',
        'vu',
        'wf',
        'ws',
        'ye',
        'yt',
        'za',
        'zm',
        'zw',
    ],

    'flags' => [
        'fa' => 'ir',
        'en' => 'gb',
        'ad' => 'ad',
        'ae' => 'ae',
        'af' => 'af',
        'ag' => 'ag',
        'ai' => 'ai',
        'al' => 'al',
        'am' => 'am',
        'ao' => 'ao',
        'aq' => 'aq',
        'ar' => 'ar',
        'as' => 'as',
        'at' => 'at',
        'au' => 'au',
        'aw' => 'aw',
        'ax' => 'ax',
        'az' => 'az',
        'ba' => 'ba',
        'bb' => 'bb',
        'bd' => 'bd',
        'be' => 'be',
        'bf' => 'bf',
        'bg' => 'bg',
        'bh' => 'bh',
        'bi' => 'bi',
        'bj' => 'bj',
        'bl' => 'bl',
        'bm' => 'bm',
        'bn' => 'bn',
        'bo' => 'bo',
        'bq' => 'bq',
        'br' => 'br',
        'bs' => 'bs',
        'bt' => 'bt',
        'bv' => 'bv',
        'bw' => 'bw',
        'by' => 'by',
        'bz' => 'bz',
        'ca' => 'ca',
        'cc' => 'cc',
        'cd' => 'cd',
        'cf' => 'cf',
        'cg' => 'cg',
        'ch' => 'ch',
        'ci' => 'ci',
        'ck' => 'ck',
        'cl' => 'cl',
        'cm' => 'cm',
        'cn' => 'cn',
        'co' => 'co',
        'cr' => 'cr',
        'cu' => 'cu',
        'cv' => 'cv',
        'cw' => 'cw',
        'cx' => 'cx',
        'cy' => 'cy',
        'cz' => 'cz',
        'de' => 'de',
        'dj' => 'dj',
        'dk' => 'dk',
        'dm' => 'dm',
        'do' => 'do',
        'dz' => 'dz',
        'ec' => 'ec',
        'ee' => 'ee',
        'eg' => 'eg',
        'eh' => 'eh',
        'er' => 'er',
        'es' => 'es',
        'et' => 'et',
        'fi' => 'fi',
        'fj' => 'fj',
        'fk' => 'fk',
        'fm' => 'fm',
        'fo' => 'fo',
        'fr' => 'fr',
        'ga' => 'ga',
        'gd' => 'gd',
        'ge' => 'ge',
        'gf' => 'gf',
        'gg' => 'gg',
        'gh' => 'gh',
        'gi' => 'gi',
        'gl' => 'gl',
        'gm' => 'gm',
        'gn' => 'gn',
        'gp' => 'gp',
        'gq' => 'gq',
        'gr' => 'gr',
        'gs' => 'gs',
        'gt' => 'gt',
        'gu' => 'gu',
        'gw' => 'gw',
        'gy' => 'gy',
        'hk' => 'hk',
        'hm' => 'hm',
        'hn' => 'hn',
        'hr' => 'hr',
        'ht' => 'ht',
        'hu' => 'hu',
        'id' => 'id',
        'ie' => 'ie',
        'il' => 'il',
        'im' => 'im',
        'in' => 'in',
        'io' => 'io',
        'iq' => 'iq',
        'ir' => 'ir',
        'is' => 'is',
        'it' => 'it',
        'je' => 'je',
        'jm' => 'jm',
        'jo' => 'jo',
        'jp' => 'jp',
        'ke' => 'ke',
        'kg' => 'kg',
        'kh' => 'kh',
        'ki' => 'ki',
        'km' => 'km',
        'kn' => 'kn',
        'kp' => 'kp',
        'kr' => 'kr',
        'kw' => 'kw',
        'ky' => 'ky',
        'kz' => 'kz',
        'la' => 'la',
        'lb' => 'lb',
        'lc' => 'lc',
        'li' => 'li',
        'lk' => 'lk',
        'lr' => 'lr',
        'ls' => 'ls',
        'lt' => 'lt',
        'lu' => 'lu',
        'lv' => 'lv',
        'ly' => 'ly',
        'ma' => 'ma',
        'mc' => 'mc',
        'md' => 'md',
        'me' => 'me',
        'mf' => 'mf',
        'mg' => 'mg',
        'mh' => 'mh',
        'mk' => 'mk',
        'ml' => 'ml',
        'mm' => 'mm',
        'mn' => 'mn',
        'mo' => 'mo',
        'mp' => 'mp',
        'mq' => 'mq',
        'mr' => 'mr',
        'ms' => 'ms',
        'mt' => 'mt',
        'mu' => 'mu',
        'mv' => 'mv',
        'mw' => 'mw',
        'mx' => 'mx',
        'my' => 'my',
        'mz' => 'mz',
        'na' => 'na',
        'nc' => 'nc',
        'ne' => 'ne',
        'nf' => 'nf',
        'ng' => 'ng',
        'ni' => 'ni',
        'nl' => 'nl',
        'no' => 'no',
        'np' => 'np',
        'nr' => 'nr',
        'nu' => 'nu',
        'nz' => 'nz',
        'om' => 'om',
        'pa' => 'pa',
        'pe' => 'pe',
        'pf' => 'pf',
        'pg' => 'pg',
        'ph' => 'ph',
        'pk' => 'pk',
        'pl' => 'pl',
        'pm' => 'pm',
        'pn' => 'pn',
        'pr' => 'pr',
        'ps' => 'ps',
        'pt' => 'pt',
        'pw' => 'pw',
        'py' => 'py',
        'qa' => 'qa',
        're' => 're',
        'ro' => 'ro',
        'rs' => 'rs',
        'ru' => 'ru',
        'rw' => 'rw',
        'sa' => 'sa',
        'sb' => 'sb',
        'sc' => 'sc',
        'sd' => 'sd',
        'se' => 'se',
        'sg' => 'sg',
        'sh' => 'sh',
        'si' => 'si',
        'sj' => 'sj',
        'sk' => 'sk',
        'sl' => 'sl',
        'sm' => 'sm',
        'sn' => 'sn',
        'so' => 'so',
        'sr' => 'sr',
        'ss' => 'ss',
        'st' => 'st',
        'sv' => 'sv',
        'sx' => 'sx',
        'sy' => 'sy',
        'sz' => 'sz',
        'tc' => 'tc',
        'td' => 'td',
        'tf' => 'tf',
        'tg' => 'tg',
        'th' => 'th',
        'tj' => 'tj',
        'tk' => 'tk',
        'tl' => 'tl',
        'tm' => 'tm',
        'tn' => 'tn',
        'to' => 'to',
        'tr' => 'tr',
        'tt' => 'tt',
        'tv' => 'tv',
        'tw' => 'tw',
        'tz' => 'tz',
        'ua' => 'ua',
        'ug' => 'ug',
        'um' => 'um',
        'us' => 'us',
        'uy' => 'uy',
        'uz' => 'uz',
        'va' => 'va',
        'vc' => 'vc',
        've' => 've',
        'vg' => 'vg',
        'vi' => 'vi',
        'vn' => 'vn',
        'vu' => 'vu',
        'wf' => 'wf',
        'ws' => 'ws',
        'ye' => 'ye',
        'yt' => 'yt',
        'za' => 'za',
        'zm' => 'zm',
        'zw' => 'zw',
    ],

    'locale_separator' => '-',

    'locale' => 'en',

    'use_fallback' => true,

    'use_property_fallback' => true,

    'fallback_locale' => 'en',

    'translation_model_namespace' => null,

    'translation_suffix' => 'Translation',

    'locale_key' => 'locale',

    'to_array_always_loads_translations' => true,

    'rule_factory' => [
        'format' => \Astrotomic\Translatable\Validation\RuleFactory::FORMAT_ARRAY,
        'prefix' => '%',
        'suffix' => '%',
    ],
];
